### PR TITLE
Refactor events dispatching

### PR DESCRIPTION
**Pull request by BitScorpio**
This is done to avoid looping through all the registered listeners and checking for their types in order to dispatch an event.

### CODE REVIEW

**Comment by d-o-g** [comment]
looks good for the most part

`Class<V> listenerClass` the type V should be a subtype of EventListener (i.e `Event<T, V extends EventListener>`)

regarding your comment in UIEvent: i imagine it would use a different instance of EventDispatcher and not the one in RSClient as that is meant for game events only. same thing sort of applies to mediator which is a communicator between the game and bot, could always abstract EventMediator (and dispatcher if needed but thats already done in a generic enough way) and have diff implementations of it

**Comment by MzScorpio** [comment]
I just noticed that the  [PreferenceEvent ](https://github.com/rs-peer/rsp3/blob/master/environment/src/main/java/org/rspeer/environment/preferences/event/PreferenceEvent.java) class extends the API's [Event ](https://github.com/rs-peer/rsp3/blob/master/api/src/main/java/org/rspeer/event/Event.java) class (which is questionable). In order to make type **V** a subtype of [EventListener](https://github.com/rs-peer/rsp3/blob/master/api/src/main/java/org/rspeer/event/listener/EventListener.java) we'll have to make [PreferenceListener](https://github.com/rs-peer/rsp3/blob/master/environment/src/main/java/org/rspeer/environment/preferences/event/PreferenceListener.java) extend **EventListener** as well (also an API class). If the API is going to get used out of the game then we might as well just have a global mediator that assembles the event from provided parameters and sends it to the global dispatcher.

We'll also have to create UI listener classes instead of just having an accept method like the one here
https://github.com/rs-peer/rsp3/blob/ec5bb9407808e3e381fb70bfee2cbd9299abb513/ui/src/main/java/org/rspeer/ui/Window.java#L17

**Comment by d-o-g** [comment]
the api is not specifically game api, there is a game package in the api but also commons and event packages which are not in game (addressed in 98085f98842c08aac6091022782627d787b9a541)

**Comment by d-o-g** [comment]
edited btw

**Comment by d-o-g** [comment]
hoyl fuck i just jacked off its everywhere l0l0l

**Comment by MzScorpio** [comment]
> 
> 
> hoyl fuck i just jacked off its everywhere l0l0l

That definitely needs to be implemented...

**Comment by BitScorpio** [comment]
Reverted that last commit as it requires a UIListener class. Going to push that tomorrow.

**Comment by MaddoxDevelopment** [comment]
I don’t think you should be making a new list on every dispatch, what’s the use case for?

**Comment by BitScorpio** [comment]
> I don’t think you should be making a new list on every dispatch, what’s the use case for?

Having more than 1 listener for the same event. For example, the client's debug RenderListener & a script's RenderListener

**Comment by MaddoxDevelopment** [comment]
Right, but you can just keep that list when they register their event, why make a unmodifiable list when you dispatch?

**Comment by BitScorpio** [comment]
> 
> 
> Right, but you can just keep that list when they register their listener, why make a unmodifiable list when you dispatch?

Because the list shouldn't be modified at all when retrieved using that method. I initially wanted to return null & run a check inside the event's dispatch method but **Collections.unmodifiableX** does not take a null parameter.

I see where you're coming from though, could check if the list is null before turning it into an unmodifiable one and if so just return a null & check for that inside the **event.dispatch()**

**Comment by BitScorpio** [comment]
A better approach would be removing the **getListeners()** method entirely and passasing the event to the dispatcher which passes it to the listeners.

**Comment by BitScorpio** [comment]
> 
> 
> A better approach would be removing the **getListeners()** method entirely and passasing the event to the dispatcher which passes it to the listeners.

Ignore that, we need to typecast the listener in order to be able to notify it. I'm messing around to find a solution

**Comment by BitScorpio** [comment]
There's a current limitation on how listeners are registered in the dispatcher.

Assume:
- **SomeListener** extends **EventListener**
- **AnotherListener** extends **SomeListener**

The dispatcher will register **AnotherListener** in the **SomeListener** group (Because **SomeListener** is the class that directly inherits from **EventListener**) therefore any **Event** that parameterizes **AnotherListener** will not be dispatched.

**Comment by Lezor91** [comment]
could switch to assigning values (id) to event types instead of using instanceof/class

**Comment by BitScorpio** [comment]
> 
> 
> could switch to assigning values (id) to event types instead of using instanceof/class

We still cannot assign these types to the listener classes since they're interfaces, and a class implementing multiple listeners will not be able to provide types for all the implemented listeners without hardcoding them in an array. I'll improve the interfaces grabbing method until we find a better alternative.

**Comment by BitScorpio** [comment]
The limitation previously mentioned is no longer an issue

**Comment by BitScorpio** [comment]
This will now sync development with master as well, had to make a few adjustments due to PR #32

**Pull request merged**
