### PR TITLE
Script loading improvements

### PR DESCRIPTION
**Pull request by BitScorpio**

### CODE REVIEW

**Comment by Lezor91** [comment]
The define is in the loader for different instances of script source (i.e RemoteScriptSource for sdn scripts in the future). Besides it seems more fundamentally correct to have the *loader* do the definitions.

As for predefined, that was originally added due to us having the idea to prepackage a few scripts with the bot. Throwing a few of the better or "official" scripts in there gives the bot a representation

**Comment by BitScorpio** [comment]
I'll add them back in an hour

**Comment by BitScorpio** [comment]
Maybe the define method should go into the ScriptSource and each SubClass should have it's own implementation. The loader  should only be dedicated to loading the source.

**Comment by Lezor91** [comment]
The ScriptProvider is responsible for loading and providing script sources, defining is part of that. We also have no idea yet how the remote script provider will work and defining those scripts may need other data which only the loader has, moving it may complicate that

**Comment by BitScorpio** [comment]
Alright I've reverted the needed commits

**Comment by BitScorpio** [comment]
Resolved conflicts, this can be merged now.

**Pull request merged**
